Add per team player stats with extra trackers
PGMDev/PGM pull request #1208
Opened 2023-07-23 22:59 UTC by Pugzy

Rewrite the stats logic so that statistics can be per team. This allows the stats at the end of the match to show contributions towards both teams.

- Introduces a table to store the team, player, stats values and create new stat entries with a reference to its global stats parent.
- Resets a player's active kills streak when switching teams.
- Store snapshot of player's name in a component inside a teams player stats.
- Rewrite team stats GUI to make use of per-team stats (no longer need to create online/observers/offline players separately.
- Attempts to fix the current issues with the team stats GUI where nicknames and skins are revealed.
- Adds extra stats related to objective completion (rather than just flags).

Still a WIP and requires a bit more testing but general feedback is more than welcome.

2023-07-23 23:51 UTC, Pablete1234 requested changes

2023-07-23 23:51 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
> +    return Tables.unmodifiableTable(stats);
keep getStats signature intact (returning global stats) and have getParticipationStats as the new one returning a table, for api backwards-compatibility

2023-07-23 23:51 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
> +                // TODO: wrong method
?

2023-07-23 23:51 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
> +    }
is this about getting the player off of a player state? If so, that's not needed, keep it as:
```suggestion
    if (event.getPlayer() != null) {
      getPlayerStat(event.getPlayer()).onWoolCapture();
    }
```

2023-08-12 21:10 UTC, Pablete1234 reviewed
just a few tweaks

2023-08-12 21:10 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/PlayerStats.java
> +    this.inTime = null;
```suggestion
    this(null, null);
```

2023-08-12 21:10 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/PlayerStats.java
> +    return (inTime == null) ? Duration.ZERO : Duration.between(inTime, Instant.now());
```suggestion
    return inTime == null ? Duration.ZERO : Duration.between(inTime, Instant.now());
```

2023-08-12 21:10 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/stats/menu/items/TeamStatsMenuItem.java
> +    this.stats = new TeamStats(team, new ArrayList<>(playerStats.values()));
i'd avoid the relocation, just pass accept a Collection<PlayerStats> in the constructor instead
```suggestion
    this.stats = new TeamStats(team, playerStats.values());
```

2023-08-23 17:40 UTC, Pablete1234 approved these changes

2023-08-23 17:40 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/goals/GoalMatchModule.java
> +    match.getWinners();
This is subtle behavior which is not great, it’s better if we could do something explicit. But I’ll still merge for now.

2023-08-23 17:41 UTC, Electroid approved these changes

2023-08-23 17:41 UTC, merged