Add a modify-lives action
PGMDev/PGM pull request #1214
Opened 2023-08-11 02:57 UTC by cswhite2000

Adds a `modify-lives` action. At @zzufx's request

You can add, subtract, or set lives.
Usage would be as follows:

```xml
<modify-lives operation="add" amount="2" show-title="true"/>
```
`show-title` is optional and can be left out
```xml
<modify-lives operation="set" amount="1"/>
or
<modify-lives operation="subtract" amount="1"/>
```

The action will act on all players in a given scope, so for example you could have a team scoped set lives to 1 that would set the lives remaining for all players to 1 after an objective is completed.

2023-08-11 09:06 UTC, Pablete1234 commented
Make number an expression supporting variables, adds alot more play

2023-08-12 12:08 UTC, Pablete1234 requested changes
Besides what i pointed out, i have doubts ablut the whole add/remove/set thing.
In the original draft for variables i had a similar system, but that eventually went out the window in favor of formulas with variables.
Want to add 5? Use `<set var="thing" value="thing + 5"/>`
Want to halve it? Use `<set var"thing" value="thing / 2">`

Its much more flexible than hard-coded allowed operations.

The biggest roadblock is lack of a way to reference lives left within that. I mentioned somewhere that it'd be nice go have nore variabke types, so you could define a: `variable id="lives" type="blitz-lives"` or similar. Some other candidates would be player curr and max health, or team score. What thks allows is to directly ooerate on blitz lives as if it was just another variable. You can arbitratily `<set var="lives" value="lives + 5">` which automatically gets you this behavior, plus you can now operate on so much more (eg: set player max heath based on amount of lives, so last live you have less max hp) or stuff like that. Also there's a consideration for potentially readonly variable types, maybe health should be readonly and can be set via a kit if you wish, etc.

Im fully aware that much of what i mentioned here is well out of scope for this pr, but im just trying to give my long-term vision on the matter, in hopes that we can get some middle ground that both aligns this towards that but doesnt necessarily mean a full rewrite

2023-08-12 12:08 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/Operation.java
> +  ADD("add", "addition", "plus"),
Why do we have 3 diff names for the same thing? Id honestly avoid giving different syntax for the same thing, decide on one

2023-08-12 12:08 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/actions/BlitzLivesAction.java
> +  private Consumer<T> chooseScopeConsumer(Class<T> cls) {
Yeah... no.
Make this a player-scoped action. If the mapdev wants it to affect all players on a team they can use switch-scope action.
If in the future we add team-scoped lives in blitz (ie: whole team shares a pool of lives, maybe mixed in with player lives too) then this would conflict with that, as now you have to break maps to decide if lives would go to the team (pool) or the player.

2023-08-12 17:13 UTC, cswhite2000 commented on core/src/main/java/tc/oc/pgm/action/Operation.java
> +  ADD("add", "addition", "plus"),
Yeah I can change it to just a single name

2023-08-12 17:13 UTC, cswhite2000 commented on core/src/main/java/tc/oc/pgm/action/actions/BlitzLivesAction.java
> +  private Consumer<T> chooseScopeConsumer(Class<T> cls) {
Will do

2023-08-12 17:23 UTC, cswhite2000 commented
I also would prefer to use variables directly for things like this, and I'm willing to go with that approach if we can come up with a suitable design.

My main sticking point for why I didn't originally go with that approach is that it seemed like I'd have to create default variables for those things and update them every time the underlying value was changed, while also adding an update for every time the variable changed to change the underlying value.

2023-08-13 04:01 UTC, Pablete1234 requested changes

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
> +    MatchPlayer matchPlayer = (MatchPlayer) context;
```suggestion
    MatchPlayer matchPlayer = context.getFilterableAncestor(MatchPlayer.class);
```
although we don't have a children that could have match player as parent and this will always return just itself, it's a safer method (won't get an illegal cast).
(note: same for getValue)

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
> +    BlitzMatchModule blitzMatchModule = matchPlayer.getMatch().needModule(BlitzMatchModule.class);
```suggestion
    BlitzMatchModule blitzMatchModule = matchPlayer.getMatch().requireModule(BlitzMatchModule.class);
```

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/Variable.java
> +  VariableType getType();
is this used anywhere? i have the feeling it's just unneeded extra code in each variable implementation

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/VariableType.java
> +  static VariableType parse(Node variableTypeNode, VariableType defaultType)
pretty sure there's XMLUtil to parse enum, you don't need all of the setup, or the stringTypeMap stuff

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/VariableType.java
> +  LIVES(MatchPlayer.class);
```suggestion
  DUMMY(DummyVariable::new, Filterable.class),
  LIVES(BlitzVariable::new, MatchPlayer.class);
```

2023-08-13 04:01 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/VariablesModule.java
> +      switch (varDef.getVariableType()) {
```suggestion
      match.getFeatureContext().add(varDef.buildInstance());
```
buildInstance method can call the builder in type with itself as parameter

2023-08-13 04:12 UTC, cswhite2000 commented on core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
> +    BlitzMatchModule blitzMatchModule = matchPlayer.getMatch().needModule(BlitzMatchModule.class);
There doesn't seem to be a method with the signature requireModule

2023-08-13 04:13 UTC, cswhite2000 commented on core/src/main/java/tc/oc/pgm/variables/Variable.java
> +  VariableType getType();
Ah no its not, I'll remove it

2023-08-13 04:17 UTC, cswhite2000 commented on core/src/main/java/tc/oc/pgm/variables/VariableType.java
> +  static VariableType parse(Node variableTypeNode, VariableType defaultType)
Ah you're correct, I'll use that

2023-08-13 04:35 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/BlitzVariable.java
> +    BlitzMatchModule blitzMatchModule = matchPlayer.getMatch().needModule(BlitzMatchModule.class);
apparently it's `moduleRequire`

2023-08-13 11:16 UTC, Pablete1234 requested changes
The one last thing i see missing is preventing variable filters for non-dummy variable types being created. If you made a blitz variable and filtered on it, it wouldn't work dynamically

2023-08-13 20:56 UTC, Pablete1234 requested changes

2023-08-13 20:56 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/variables/VariableType.java
> +  }
```suggestion
```

2023-08-13 23:53 UTC, Pablete1234 approved these changes
Great work

2023-08-19 15:51 UTC, Pablete1234 commented
Please note, given recent changes, this should be merged alongside #1220. Syntax has changed.

2023-08-23 17:42 UTC, Electroid approved these changes

2023-08-23 17:42 UTC, merged