Add team scale command & add admin chat feedback for other commands
PGMDev/PGM pull request #1247
Opened 2023-09-23 02:23 UTC by cswhite2000

Adds a team / ffa scale command to proportionally scale team sizes to their current sizes.
- `/team scale <team> <factor>`
- `/ffa scale <factor>`

Also moves command feedback for certain commands to admin chat.
These are:
- Team management commands
- `/cancel`
- `/start`
- `/timelimit`

2023-10-08 16:53 UTC, Pablete1234 requested changes

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/CancelCommand.java
> +            "admin.cancelCountdowns.announce", PlayerComponent.player(sender, NameStyle.FANCY)),
```suggestion
            "admin.cancelCountdowns.announce", player(sender, NameStyle.FANCY)),
```
We use static imports for components

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/StartCommand.java
> +            TemporalComponent.duration(duration, NamedTextColor.AQUA)),
same here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +            PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +        translatable("match.shuffle.announce.ok", PlayerComponent.player(sender, NameStyle.FANCY)),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +            PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +              PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +              PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +              PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +              PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TeamCommand.java
> +              PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 16:53 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/command/TimeLimitCommand.java
> +            PlayerComponent.player(sender, NameStyle.FANCY),
and here

2023-10-08 20:21 UTC, Pablete1234 approved these changes

2023-10-09 19:17 UTC, Electroid approved these changes

2023-10-09 19:18 UTC, merged