feat: support switch-case replacements and definitions at root level
PGMDev/PGM pull request #1459
Opened 2024-12-15 16:35 UTC by TTtie

Adds support for switch-case style replacement in message actions, inspired by pattern matching found in modern programming languages, for example (preliminary syntax, some details may be subject to change):

```xml
<message text="The outcome is {outcome}">
    <replacements>
        
        <switch id="outcome" value="variable">
            
            <case match="0" result="Outcome 1"/>
            
            
            <case match="1" filter="only-team-1" result="`aOutcome 2"/>
            
            
            <case filter="only-team-2" result="`bOutcome 3"/>
            
            
            <case>
                <match>2..5</match>
                <filter>
                    <all id="not-moving">
                        <variable var="player.vel_x">0</variable>
                        <variable var="player.vel_y">..0</variable>
                        <variable var="player.vel_z">0</variable>
                    </all>
                </filter>
                <result>`cOutcome 4</result>
            </case>
            
            
            <fallback>`dA fallback outcome</fallback>
        </switch>
    </replacements>
</message>
```

Additionally, replacements can now be specified at the root level:
```xml
<map>
    <replacements>
        
        <decimal id="decimal" value="money" scope="player" format="0.00"/>
        
        
        <switch id="team">
            <case filter="only-team-1" result="`aLime"/>
        </switch>
    </replacements>
    <actions>
        <action id="action" scope="match">
            <message text="The variable is {variable} and your team is {team}!">
                <replacements>
                    
                    <replacement id="variable">decimal</replacement>
                    <replacement id="team">team</replacement>
                </replacements>
            </message>
        </action>
    </actions>
</map>
```

2024-12-16 19:02 UTC, Pablete1234 requested changes

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/Replacement.java
> +  ComponentLike replace(S audience);
You're not *replacing* you're creating a component, so i feel calling this method replace is a bit misleading
Maybe `create` or `get` would fit better

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/Replacement.java
> +  Class<S> getScope();
You can likely get away with not having a scope, but rather a *checking* function, since some replacements dont need any specific scope.

Think of it in the same spirit as `respondsTo` in filters.

Reason behind this is that if a replacement works for `Match` it should also work for party or player, there's no reason it shouldn't, at least not with the current replacements. If in the future a new replacement requires something else you can still implement that replacement as more strict, but for the ones we have it should be more lenient

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +    var formatString = parser.string(el, "format").attr().orNull();
`.optional().map(DecimalFormat::new).orElse(DEFAULT_FORMAT);`

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +    Class<T> _scope = scope == null ? (Class<T>) (Object) Filterable.class : scope;
You're doing the most scope-tricks for the replacement that needs them the least. The player replacement can literally work with any scope, it shouldnt even need to do any figuring-out

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +      if (filter != null) {
This isn't the place to write this code, make this part of the filter parser so you can `parser.filter(el, "filter").respondsTo(scope).orNull()`

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +          filter == null ? StaticFilter.ALLOW : filter));
You can use `orAllow()` at the end of the filter parser to avoid the nullcheck

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/Replacement.java
> +public interface Replacement<S extends Audience> extends FeatureDefinition {
scopes should be `extends Filterable<?>`

2024-12-16 19:02 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +  }
As mentioned before, relegate this to a method within the replacement; let it decide what the logic for rejecting a scope should be

2024-12-22 15:45 UTC, Pablete1234 submitted a review, later dismissed

2025-06-03 01:30 UTC, calcastor commented
Testing with changes from [this repo](https://github.com/TTtie/occ-community-maps/commits/refactor/use-switch-case-replacements/), with the exception of Grand Dueling and Chromatic Conquest which differ too much upstream for me to rebase the changes right now, everything seems to work as intended.

2025-07-06 19:31 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/util/xml/parsers/FilterBuilder.java
> +                    + Filterables.scope(definition).getSimpleName()
This can and will throw for filters that do not belong to any scope, which is possible in non-dynamic filters.

2025-07-07 13:30 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +      });
If you don't specify a value, and do specify a match, you could end up with a weird error message:

"Unused node 'match'" alongside an "At least a filter or a match..." which may leave you puzzled if you were a mapdev

maybe an option would be:
```suggestion
      var filterParse = parser.filter(innerEl, "filter");
      var filter = valueRange == null ? filterParse.required() : filterParse.orAllow();
```
which will just mark filter as required (without mentioning match at all) if you've not specified match.
not sure if it's really better or worse, maybe the err message should be different depending on if value is specified or not? i really don't know what's better

2025-07-07 13:46 UTC, TTtie commented on core/src/main/java/tc/oc/pgm/action/replacements/ReplacementParser.java
> +      });
> If you don't specify a value, and do specify a match, you could end up with a weird error message:
> 
> "Unused node 'match'" alongside an "At least a filter or a match..." which may leave you puzzled if you were a mapdev

That will never happen. Parsing errors interrupt the whole map loading process, and unused node warnings are the very last step in that process. The error message probably needs a rewrite given that `match="..."` is ignored when there's no value though.

2025-07-07 19:02 UTC, Pablete1234 approved these changes

2025-07-07 19:02 UTC, merged