Add option to show ping in tablist
PGMDev/PGM pull request #585
Opened 2020-08-02 04:23 UTC by Pablete1234

Adds a config option to enable displaying real players' ping on the tablist, will not work on the 1.7 legacy tablist and there are no plans to ever port it there

2020-08-02 04:29 UTC, Electroid commented
I guess.. why not always show it? If we're caching it, I don't see a reason to disable it. Just seems like a silly config option.

2020-08-02 04:45 UTC, Pablete1234 commented
You may want players not to be annoying about what other players' ping are, this has happened before and i think it may be in some public servers' interest not to show it

2020-08-02 15:27 UTC, Pugzy commented
My previous comments on this feature over at https://github.com/PGMDev/PGM/pull/492

2020-08-02 15:33 UTC, Pablete1234 commented
The ping is periodically updated and kept on sync, so that one isn't an issue. That is how vanilla minecraft does it too, just send a packet to update ping every so often.

Regarding consistency and visual clutter, some players actually seem to care about knowing this value, if you're lagging and you see yourself on lower than 5 bars you know ur not doing good.

Precisely because there can be some controversy arround this, i've made it a server setting that, in fact, is disabled by default. But i've herd a few memberos of the community ask for this feature and if they actually want it, and many use BLC or other mods that show actual ping values, they'd rather see this.

2020-08-03 14:48 UTC, Electroid requested changes

2020-08-03 14:48 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/PGMConfig.java
> +    this.showTabListPing = parseBoolean(config.getString("ui.tablist-ping", "false"));
I think the default should be `true`.

2020-08-03 14:48 UTC, Electroid commented on core/src/main/resources/config.yml
> +  tablist-ping: false # Should tab list show real ping?
Just call this `ping`.

2020-08-03 15:18 UTC, Electroid approved these changes

2020-08-03 15:18 UTC, merged