Prevent team griefing on scored matches
PGMDev/PGM pull request #606
Opened 2020-08-11 05:51 UTC by Pablete1234

A new config option for under how many (negative) points, a player should be kicked out of the match and not allowed to rejoin. This prevents team griefing in TDM dying to the enemy team doesn't substract score so that won't affect this, only purposely suiciding will end up triggering it

![image](https://user-images.githubusercontent.com/11789291/89862037-66446080-dba7-11ea-92c3-3c484a4a3ff7.png)

2020-08-11 05:54 UTC, Indicardo commented
I think the default -10 "grief score" is too much, as for a group of 4 that would result in -40 points

2020-08-11 06:45 UTC, Pablete1234 commented
> I think the default -10 "grief score" is too much, as for a group of 4 that would result in -40 points

While i agree it may be a bit too much, i'd rather keep the default on a number that is pretty much guaranteed not to be an issue that will affect anyone, can be tweaked/lowered for different scenarios, like public matches

2020-08-11 07:03 UTC, KingOfSquares commented
This feels like a moderation thing and not a PGM feature. Maybe put it in community?

2020-08-11 07:23 UTC, Pablete1234 commented
> This feels like a moderation thing and not a PGM feature. Maybe put it in community?

I think this is as much moderation as preventing breaking your own core is, or tnt defusing, it doesn't issue any punishment it just prevents you from keeping on doing it

2020-08-11 18:52 UTC, KingOfSquares commented
Then maybe a rephrasing, `You made a negative impact` sound like the plugin judging you for being bad :joy:

Maybe something more `[...]because of intentional misfit[...]` or something giving the vibe of intentional bad actions

2020-08-12 04:15 UTC, Pablete1234 commented
> Then maybe a rephrasing, `You made a negative impact` sound like the plugin judging you for being bad 
> 
> Maybe something more `[...]because of intentional misfit[...]` or something giving the vibe of intentional bad actions

Well the point is the plugin isn't 100% sure, so it's just a bit more of an open "you weren't helping your team with how you played", unsure if intentional or not

2020-08-17 15:35 UTC, Electroid requested changes

2020-08-17 15:35 UTC, Electroid commented on util/src/main/i18n/templates/join.properties
> +join.err.teamGrief = You made a negative impact for your team and can no longer play this match
You caused too much negative impact to play this match

2020-08-19 15:31 UTC, merged