Add map created date
PGMDev/PGM pull request #617
Opened 2020-08-18 01:50 UTC by jacobbearden

Signed-off-by: Jacob Bearden <jacob@bearden.io>

Closes #564 

![image](https://user-images.githubusercontent.com/5340692/90461181-d597e400-e0c2-11ea-9d4c-a5a25bf277c0.png)

2020-08-18 08:46 UTC, Pablete1234 requested changes

2020-08-18 08:46 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/api/map/MapInfo.java
> +  Date getCreated();
Use a java 8 `LocalDate`

2020-08-19 01:32 UTC, Pablete1234 approved these changes

2020-08-19 15:33 UTC, Electroid approved these changes
:rocket:

2020-08-19 15:33 UTC, merged