Send TNT alert in admin chat
PGMDev/PGM pull request #618
Opened 2020-08-18 02:33 UTC by jacobbearden

Signed-off-by: Jacob Bearden <jacob@bearden.io>

Closes #557 

![image](https://user-images.githubusercontent.com/5340692/90463688-cddb3e00-e0c8-11ea-8a1c-66a099affa32.png)

2020-08-18 08:51 UTC, Pablete1234 requested changes

2020-08-18 08:51 UTC, Pablete1234 commented on util/src/main/i18n/templates/moderation.properties
> +moderation.defuse.alert.player = {0} defused {1}'s TNT.
```suggestion
moderation.defuse.alert.player = {0} defused {1}'s {2}.
```
TNT should be localized aswell, using minecraft's name

2020-08-18 08:51 UTC, Pablete1234 commented on util/src/main/i18n/templates/moderation.properties
> +moderation.defuse.alert.world = {0} defused world TNT.
same as above

2020-08-18 08:51 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/listeners/AntiGriefListener.java
> +                owner.getName(NameStyle.FANCY)),
```suggestion
                owner.getName(NameStyle.FANCY),
                MinecraftTranslations.getEntity(entity.getType()).color(TextColor.DARK_RED)),
```
Add the translatable component for the TNT name

2020-08-18 08:51 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/listeners/AntiGriefListener.java
> +                "moderation.defuse.alert.world", TextColor.WHITE, clicker.getName(NameStyle.FANCY)),
same as above

2020-08-18 17:55 UTC, Pugzy commented
Not a clue why I didn't PR this [Pugzy/defuse-alert](https://github.com/Pugzy/PGM/tree/defuse-alert) beat me to the punch! 
Just don't quit after leaving the comments above unresolved for a month.

2020-08-18 20:18 UTC, applenick requested changes

2020-08-18 20:18 UTC, applenick commented on core/src/main/java/tc/oc/pgm/listeners/AntiGriefListener.java
> +                TextColor.WHITE,
```suggestion
                TextColor.GRAY,
```
Consider the gray chat color so formatting is more aligned with other admin broadcasts (e.g /sn) 🙂

2020-08-18 20:20 UTC, applenick commented on core/src/main/java/tc/oc/pgm/listeners/AntiGriefListener.java
> +                "moderation.defuse.alert.world", TextColor.WHITE, clicker.getName(NameStyle.FANCY)),
See other comment about color

2020-08-18 22:23 UTC, applenick approved these changes

2020-08-19 01:32 UTC, Pablete1234 approved these changes

2020-08-19 15:28 UTC, Electroid approved these changes

2020-08-19 15:29 UTC, merged