./modes should act like ./mode list
PGMDev/PGM pull request #791
Opened 2021-02-02 12:04 UTC by dentmaged

`/modes` will send now the user the list of modes (just like `/mode list`).

2021-02-02 12:14 UTC, Pablete1234 commented
Make it so `mode` and `modes` are just aliases for the same thing, and the default if no subcommand is passed is showing the list

2021-02-02 17:16 UTC, CoWinkKeyDinkInc commented on core/src/main/java/tc/oc/pgm/command/ModesCommand.java
> +      desc = "List all objectivs modes",
typo

2021-02-02 17:17 UTC, CoWinkKeyDinkInc commented
This was something that has been bothering me, I like this.

2021-02-03 15:01 UTC, Pablete1234 requested changes
The implementation of all the command stuff does not belong in PGM, it belongs in intake

2021-02-04 19:49 UTC, AustinLMayes commented
`@DefaultCommand` is generic enough to exist in the base intake project itself.

2021-02-13 16:19 UTC, Electroid commented
> `@DefaultCommand` is generic enough to exist in the base intake project itself.

Agreed, let's add this to `intake`.

2021-02-13 16:20 UTC, closed without merging