Add team checks when vanishing players
PGMDev/PGM pull request #792
Opened 2021-02-04 20:10 UTC by Pugzy

Vanish logic currently assumes all players are in observers and even attempts to force this inside the `setVanished` method.

Plugins such as `Events` can allow for a situation where a player is joining the match assigned to a team, it does this by modifying the initial team of the `MatchPlayerAddEvent` to the team they are assigned to. 

This can also cause a situation where a vanish player is forced on to a team on match cycle or on registering a tournament team.

This maintains the logic that already exists, however, stops processing the `PlayerJoinEvent` logic if the player is on a team.
And unvanishes the player with a join message if the player is set to a team from a vanished state in the `PlayerJoinEvent`.

Signed-off-by: Pugzy <pugzy@mail.com>

2021-02-04 20:19 UTC, Pablete1234 requested changes

2021-02-04 20:19 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/community/features/VanishManagerImpl.java
>    @EventHandler
This event could be handled before the initial party is set to be a competitor, missing this logic. Make this happen on monitor

2021-02-04 22:47 UTC, Pablete1234 approved these changes

2021-02-05 02:04 UTC, Electroid approved these changes

2021-02-05 02:04 UTC, merged