Rework stats and allow showing own stats
PGMDev/PGM pull request #805
Opened 2021-02-13 18:15 UTC by Pablete1234

Moves the stats displaying to an event, which can be cancelled or thrown by 3rd party plugins to decide when stats show, additionally, PGM has a config for when it automatically should be shown, and the event itself has settings for what to show.

![image](https://user-images.githubusercontent.com/11789291/107857623-b25eaf00-6e2f-11eb-8245-8c63db84c95f.png)
(the pic is in spanish due to local server but it shouldn't be a big issue)

2021-02-13 19:01 UTC, Pugzy reviewed
Using the term `best` over `high` may be more explanatory i.e ui.stats.show-best

2021-02-13 19:01 UTC, Pugzy commented on core/src/main/java/tc/oc/pgm/PGMConfig.java
> +    this.statsShowHigh = parseBoolean(config.getString("ui.stats.show-high", "true"));
Using `best` over high may be more explanatory i.e `ui.stats.show-best`

2021-02-14 17:19 UTC, Electroid requested changes
Also remove the `server/sportpaper.jar`, maybe add it to `.gitignore`

2021-02-14 17:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/api/Config.java
> +  int showStatsAfter();
Let's do `Duration` here.

2021-02-14 17:19 UTC, Electroid commented on core/src/main/resources/config.yml
> +  stats:
Let's move this to its own section, so not `ui.stats`, just `stats`.

2021-02-14 17:19 UTC, Electroid commented on core/src/main/resources/config.yml
> +  stats:
```yml
stats:
  verbose: true
  show-after: 3s
  show-best: true
  show-own: true
```

2021-02-14 17:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/stats/StatsDisplayEvent.java
> +package tc.oc.pgm.stats;
This needs to be in `tc.oc.pgm.api.match.event`

2021-02-14 17:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/stats/StatsDisplayEvent.java
> +public class StatsDisplayEvent extends MatchEvent implements Cancellable {
`MatchStatsEvent`

2021-02-14 17:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/stats/StatsMatchModule.java
> +      // bow
These comments can be removed, they don't add much

2021-02-15 16:53 UTC, Electroid approved these changes

2021-02-15 16:54 UTC, merged