Add Effect Filter
PGMDev/PGM pull request #810
Opened 2021-02-16 11:21 UTC by alexsosnovsky

The new `has-effect` filter returns `ALLOW` if the player has an effect of the same type and amplifier, and greater or equal duration compared to the filter's specified effect.

Syntax example:
```xml
<filters>
    <has-effect id="filter1">
        <effect duration="0s" amplifier="4">saturation</effect>
    </has-effect>
    <has-effect id="filter2">
        <effect duration="30s" amplifier="1">water breathing</effect>
    </has-effect>
    <has-effect id="filter3">
        <effect duration="0s" amplifier="2">night vision</effect>
    </has-effect>
</filters>
```

2021-02-16 11:52 UTC, Pablete1234 commented
I do not see the point in having a filter with effects as children, i think no other filter does this, instead, it's the filter itself that has the properties. 
Also, there's no use for has-*, for example team filter is simply team, even if the name itself is reused elsewhere
```xml
<filters>
    <effect id="filter1" duration="0s" amplifier="4">saturation</effect>
    <effect id="filter2" duration="30s" amplifier="1">water breathing</effect>
    <effect id="filter3" duration="0s" amplifier="2">night vision</effect>
</filters>
```

Regarding duration, a filter with a *specific* duration is of little use, it should probably be a range: `duration="2s..15s"` or `duration="2s.."`

2021-02-16 12:00 UTC, Pugzy commented
Not sure if these exists in this version of PGM but it looks like ranges and comparisons were implemented like so https://pgm.dev/docs/modules/mechanics/filters/#random-filter which may be worth replicating as the syntax used in the comment above.

2021-02-16 14:03 UTC, alexsosnovsky commented
> I do not see the point in having a filter with effects as children, i think no other filter does this, instead, it's the filter itself that has the properties.
> Also, there's no use for has-*, for example team filter is simply team, even if the name itself is reused elsewhere
> Regarding duration, a filter with a _specific_ duration is of little use, it should probably be a range: `duration="2s..15s"` or `duration="2s.."`

I've updated it to simply use the `<effect/>` tag. I also added optional `min-duration` and `max-duration` attributes so that a range can be created easily.


> Not sure if these exists in this version of PGM but it looks like ranges and comparisons were implemented like so https://pgm.dev/docs/modules/mechanics/filters/#random-filter which may be worth replicating as the syntax used in the comment above.

This looks interesting but I felt it was simpler and more intuitive to just have `min-duration` and `max-duration` attributes which take normal duration strings as input.

2021-02-18 04:44 UTC, Pablete1234 requested changes

2021-02-18 04:44 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/FilterParser.java
> +    Attribute minAttribute = el.getAttribute("min-duration");
Make use of PGM nodes  instead of XML attributes, eg:: `XMLUtils.parseDuration(Node.fromAttr(el, "min-duration"))`

2021-02-18 10:06 UTC, Pablete1234 requested changes

2021-02-18 10:06 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/HasEffectFilter.java
> +public class HasEffectFilter extends ParticipantFilter {
```suggestion
public class EffectFilter extends ParticipantFilter {
```

2021-02-18 10:06 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/HasEffectFilter.java
> +  protected final long maxDuration;
Use an actual `Range<Long>`, pass it as part of the constructor

2021-02-18 10:06 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/HasEffectFilter.java
> +          && ((maxDuration == -1) || (effect.getDuration() <= maxDuration))) {
This logic will be greatly simplified with the range, `range.contains(effect.getDuration())`

2021-02-18 10:06 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/FilterParser.java
> +    Duration maxDuration = XMLUtils.parseDuration(Node.fromAttr(el, "max-duration"));
Create a Range.atMost, Range.atLeast, or Range.closed based on if the durations are present or not, and use that in the filter

2021-02-18 10:06 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/FilterParser.java
> +    boolean amplifier = Node.fromAttr(el, "amplifier") != null ? true : false;
```suggestion
    boolean amplifier = Node.fromAttr(el, "amplifier") != null;
```

2021-02-19 06:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/EffectFilter.java
> +          && duration.contains((long) effect.getDuration())) {
I was under the impression that getDuration was a long, seems like it's an int, so the Range should also be a `Range<Integer>`, and you should do the cast in the parser instead, but it's a somewhat minor issue

2021-02-19 07:20 UTC, Pablete1234 approved these changes

2021-02-26 00:18 UTC, Electroid approved these changes

2021-02-26 00:19 UTC, merged