Fix class confirm message
PGMDev/PGM pull request #857
Opened 2021-04-23 14:10 UTC by KingOfSquares

Fixes this bug:
![2021-04-22_12 58 02](https://user-images.githubusercontent.com/19822231/115883465-17490d80-a44e-11eb-922b-e9029cc28dca.png)

Didn't test but I mean :shrug:
Signed-off-by: KingSimon <19822231+KingOfSquares@users.noreply.github.com>

2021-04-23 14:41 UTC, Pablete1234 requested changes
You should probably test it

2021-04-23 14:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/picker/PickerMatchModule.java
> +                        text(name, NamedTextColor.GREEN))
```suggestion
                        translatable("match.class.ok", NamedTextColor.GOLD,
                        text(name, NamedTextColor.GREEN))
```

2021-04-27 17:28 UTC, KingOfSquares commented on core/src/main/java/tc/oc/pgm/picker/PickerMatchModule.java
> +                        text(name, NamedTextColor.GREEN))
wait... 🤔

2021-05-07 17:12 UTC, KingOfSquares commented
Lets pretend like I managed to do this first try....

2021-05-08 13:40 UTC, Pablete1234 approved these changes

2021-05-13 23:04 UTC, Electroid approved these changes

2021-05-13 23:04 UTC, merged