Add dynamic kit rules
PGMDev/PGM pull request #932
Opened 2021-10-28 19:58 UTC by Pugzy

## Dynamic kits 🔮👕🎉  

The PR implements dynamic kits in the same fashion as Overcast Network Project Ares did.

Let's you `give`, `lend`, and `take` a kit based on a filter rising or falling.

```xml
<kits>
    
    <lend kit="jumper-kit" filter="carrying-gold" />
    <give kit="regen-kit" filter="holding-redstone" />
    
    <take>
        <kit>
            <fly/>
        </kit>
        <filter>
            <flag-carried>flag</flag-carried>
        </filter>
    </take>
    ...
</kits>
```

Not to be confused with the documented but 'deprecated' docs syntax http://docs.oc.tc/modules/kits confirmed as incorrect by Mitch (being the main user of the feature) and Pablo (checking the original commit history and PR to change).

Only a few maps used this on OCN (three total I believe) as it was a relatively new feature so if not implemented like for like the impact would be a couple of Arcade maps 🤷 that haven't been played in years.
 
Open to opinions on a better XML syntax if anyone has any ideas. I had wanted to use an `<apply>` to apply kit rules in the same way a filter is applied to a region but the above seemed like the simplest approach.

Signed-off-by: Pugzy <pugzy@mail.com>

2021-10-28 21:19 UTC, Electroid requested changes

2021-10-28 21:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/kits/KitRule.java
> +  public void load(FilterMatchModule fmm) {
I'm not sure this should exist in a `FeatureDefinition`. It's a detail of the match module.

2021-10-28 21:19 UTC, Electroid commented on core/src/main/java/tc/oc/pgm/kits/KitMatchModule.java
> +    kitRules.forEach(kitRule -> kitRule.load(fmm));
For loop.

2021-11-06 04:35 UTC, Electroid approved these changes

2021-11-06 09:12 UTC, mitchts commented
One difference I have noticed between this version of dynamic kits and the previous implementation is that you can't trigger a kit to apply immediately as the match starts. 

Take this filter from Build: Parkour which used to apply a kit immediately as the match began via `<give .../>`

```xml
<all id="build-spawn-kit">
    <not>
        <time>3s</time>
    </not>
    <region id="all-arenas-whole" />
    <participating />
    <match-running />
</all>
```

Altering this filter to allow after 1 second applies the kit to the player as expected, however.

2021-11-06 12:54 UTC, Pablete1234 commented
I think match-running filter may not exist in this pgm version

2021-11-13 17:36 UTC, merged