Add GoalQuery to PGM api
PGMDev/PGM pull request #987
Opened 2022-04-14 22:18 UTC by KingOfSquares

Signed-off-by: KingSimon <19822231+KingOfSquares@users.noreply.github.com>

2022-04-15 09:41 UTC, Pablete1234 requested changes
You should use probably be using generics as they are meant to be used, not just as wildcards everywhere

2022-04-15 09:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/api/filter/query/GoalQuery.java
> +  Goal<? extends GoalDefinition> getGoal();
```suggestion
public interface GoalQuery<T extends GoalDefinition> extends MatchQuery {
  Goal<T> getGoal();
```

2022-04-15 09:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/query/GoalQuery.java
> +  private final Goal<? extends GoalDefinition> goal;
```suggestion
public class GoalQuery<T extends GoalDefinition> extends MatchQuery implements tc.oc.pgm.api.filter.query.GoalQuery<T> {
  private final Goal<T> goal;
```

2022-04-15 09:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/query/GoalQuery.java
> +  public GoalQuery(Goal<? extends GoalDefinition> goal) {
```suggestion
  public GoalQuery(Goal<T> goal) {
```

2022-04-15 09:41 UTC, Pablete1234 commented on core/src/main/java/tc/oc/pgm/filters/query/GoalQuery.java
> +  public Goal<? extends GoalDefinition> getGoal() {
```suggestion
  public Goal<T> getGoal() {
```

2022-04-15 16:40 UTC, KingOfSquares commented
> You should use probably be using generics as they are meant to be used, not just as wildcards everywhere

Good point.

2022-04-21 01:14 UTC, Pablete1234 approved these changes

2022-05-13 02:38 UTC, Electroid approved these changes

2022-05-13 02:39 UTC, merged